### ISSUE TITLE
Can't run unit tests: Could not start application exq_scheduler

### ISSUE THREAD

**Issue by tnaftali** [activesphere/exq-scheduler#37]
I get the following error when trying to run the tests:
```
** (Mix) Could not start application exq_scheduler: exited in: ExqScheduler.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.Stream, DBConnection.PrepareStream, Timex.Interval, Floki.HTMLTree, Scrivener.Page, Jason.OrderedObject, HashSet, Range, Map, Function, List, Stream, Date.Range, HashDict, GenEvent.Stream, MapSet, File.Stream, IO.Stream
            (elixir 1.11.2) lib/enum.ex:1: Enumerable.impl_for!/1
            (elixir 1.11.2) lib/enum.ex:196: Enumerable.slice/1
            (elixir 1.11.2) lib/enum.ex:819: Enum.empty?/1
            (exq_scheduler 1.0.0) lib/exq_scheduler.ex:21: ExqScheduler.start_link/1
            (kernel 7.1) application_master.erl:277: :application_master.start_it_old/4
```

I've added `Exq.Mock.start_link(mode: :fake)` to `test_helper.exs`, but I'm not being able to mock the scheduler as well.

**Comment by ananthakumaran** [comment]
try to add the following to config/test.exs

```elixir
config :exq_scheduler,
  start_on_application: false
```

**Comment by tnaftali** [comment]
Thank you!
